In [ ]:
#ARRAY SELECTION
import numpy as np

BOOLEAN MASKING (ARRAY SELECTION)

In [ ]:
x=np.arange(1,11)

In [ ]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x.ndim

1

In [ ]:
x.size

9

In [ ]:
a=list(range(1,11))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a*4

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10]

In [ ]:
x*4

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [ ]:
x>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
x<5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [ ]:
# Condition returns boolean array
mask=x>5


In [ ]:
mask

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
# Boolean indexing
x[mask]

array([ 6,  7,  8,  9, 10])

In [ ]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b=x%2==0

In [ ]:
x[b]

array([ 2,  4,  6,  8, 10])

STRING ARRAY OPERATIONS


In [ ]:
w=np.array(['raj','roy','ram','raj'])


In [ ]:
w

array(['raj', 'roy', 'ram', 'raj'], dtype='<U3')

In [ ]:
# Comparison on string arrays
w=='raj'

array([ True, False, False,  True])

In [ ]:
# Filtering
q=w=='raj'

In [ ]:
w[q]

array(['raj', 'raj'], dtype='<U3')

In [ ]:

w[w!='roy']

array(['raj', 'ram', 'raj'], dtype='<U3')

In [ ]:
# Replace values using condition
w[w!='raj']='meet'

In [ ]:
w

array(['raj', 'mee', 'mee', 'raj'], dtype='<U3')

In [ ]:
# unique() → removes duplicates
np.unique(w)

array(['mee', 'raj'], dtype='<U3')