In [ ]:
import numpy as np


SPECIAL ARRAYS

* empty() → creates array without initializing values
* ones() → array filled with ones
* eye() → identity matrix

In [ ]:
#EMPTY
np.empty([2,3])

array([[4.65818443e-315, 0.00000000e+000, 6.78012734e-310],
       [5.76313742e-317, 6.78010393e-310, 5.30907923e-317]])

In [ ]:
#ZEROS
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([3,2],dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
#ONES
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
#EYES
np.eye(1)

array([[1.]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

LINSPACE
* linspace() → evenly spaced values

In [ ]:
#linspace
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [ ]:
#LINSPACE
np.linspace(1,55,5)

array([ 1. , 14.5, 28. , 41.5, 55. ])

In [ ]:
np.linspace(11,20,5)

array([11.  , 13.25, 15.5 , 17.75, 20.  ])

In [ ]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

INDEXING

In [ ]:
a=np.array([1,2,3,4,5])


In [ ]:
b=np.arange(1,6)

In [ ]:
a[3]   # access single element

np.int64(4)

In [ ]:
b[3]

np.int64(4)

In [ ]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
x[1]  # row

array([4, 5, 6])

In [ ]:
x[1,1]  #element at row 1, column 1

np.int64(5)

In [ ]:

x[2,1  ]

np.int64(8)

# SLICING

In [ ]:

x[ :2, :2]

array([[1, 2],
       [4, 5]])

In [ ]:
x[1:, :2]

array([[4, 5],
       [7, 8]])

In [ ]:
x[1:, 0:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[:1, 1:]

array([[2, 3]])

In [ ]:
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Assigning single value to multiple elements
m=np.arange(1,16).reshape(5,3)
m


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [ ]:
m[0:3:2,1:]

array([[2, 3],
       [8, 9]])

In [ ]:
m[0:4:3,1:]

array([[ 2,  3],
       [11, 12]])

In [ ]:
m[0:5:2,0:1]

array([[ 1],
       [ 7],
       [13]])

In [ ]:
m[0:5,1:2]

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [ ]:
m[2:5:2, 1:]=55
m

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7, 55, 55],
       [10, 11, 12],
       [13, 55, 55]])

BROADCASTING

In [ ]:
#manipulation of array

arr=np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#SLICING+BROADCASTING
arr[0: 5]=100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
m[0:5,0:1]=99
m

array([[99,  2,  3],
       [99,  5,  6],
       [99, 55, 55],
       [99, 11, 12],
       [99, 55, 55]])

In [ ]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
x=np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
x.shape[0]

10

In [ ]:
x.shape[1]

10

In [ ]:
l=x.shape[1]
l

10

In [ ]:
for i in range (l):
  x[i]=i

In [ ]:
for i in range (l):
  x[i]=l

In [ ]:
x

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [ ]:
b = np.arange(3).reshape(1, 1, 3)
b

array([[[0, 1, 2]]])