In [1]:
#IMPORTING THE NUMPY LIBRARY
# NumPy is used for numerical operations and arrays
import numpy as np


In [ ]:
np.array([[1,2,3],[4,5,6]])

# ARRAY CREATION

In [ ]:
#CREATING 2D ARRAY
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# SHAPE USE TO CHECK SHAPE OF ARRAY
a.shape
#OP:-(2,3)   2 REPERESNTS NUMBER OF ROWS ,3 REPRESENTS NUMBER OF COLUMNS.

(2, 3)

In [ ]:
#SIZE RETURNS THE TOTAL NUMBER OF ELEMENTS IN ARRAY .
a.size


6

RESHAPING ARRAYS

In [ ]:
#WE USE RESHAPE TO CONVERT OUR ARRAY FROM 1D TO 2D OR ANY OTHER ARRAY SHAPE.
#IN SHORT WE CAN CHANGE SHAPE OF OUR ARRAY.
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.shape=(3,2)

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

TRANSPOSE

In [ ]:
# Transpose swaps rows and columns
a=np.array([[1,2,3],[4,5,6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#ndims
#number of dimensions
a.ndim

2

RANGE-BASED ARRAY CREATION

In [ ]:
#functions of numpy
# arange() creates array with range of values
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [ ]:
x=np.arange(1,7)

In [ ]:
x.shape

(6,)

In [ ]:
x.ndim

1

In [ ]:
# Reshaping into 2D
x=np.arange(1,7).reshape(2,3)

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y=np.arange(7,13).reshape(2,3)

In [ ]:
y

array([[ 7,  8,  9],
       [10, 11, 12]])

CONCATENATION & STACKING

In [2]:
# concatenate() joins arrays along axis 0 (default)

z=np.concatenate((x,y))

NameError: name 'x' is not defined

In [ ]:
z

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
z.shape

(4, 3)

In [ ]:
z.size

12

In [ ]:
z.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:

x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#hstack
np.hstack((x))

array([1, 2, 3, 4, 5, 6])

In [ ]:

#hstack → horizontal stacking (columns)
np.hstack((x,y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
#vstack
np.vstack((x))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# vstack → vertical stacking (rows)

np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m=np.arange(1,7)

In [ ]:
m

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.vstack((m))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

APPEND, INSERT, DELETE

In [ ]:
#append
# append() adds values at end (creates new array)
np.append(m,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
q=np.append(m,[7,8,9])

In [ ]:
q

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#insert
# insert() inserts value at specific index
c=np.arange(2,6)

In [ ]:
c

array([2, 3, 4, 5])

In [ ]:
np.insert(c,0,1)

array([1, 2, 3, 4, 5])

In [ ]:
c

array([2, 3, 4, 5])

In [ ]:
#delete
# delete() removes elements by index
r=np.arange(1,7)

In [ ]:
r

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.delete(r,[2,3,4,5])

array([1, 2])

In [ ]:
r

array([1, 2, 3, 4, 5, 6])